### ISSUE TITLE
Incompatibility with Test-Kitchen 1.3.1 (:chef_omnibus_root ?)

### ISSUE THREAD

**Issue by jmauro** [criteo/kitchen-vagrant_winrm#8]
Hey,

Since the lastest version of test-kitchen there is an issue with the default value for 'chef_omnibus_root':
``` ruby
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: Failed to complete #converge action: [Expected process to exit with [0], but received '1'
---- Begin output of vagrant winrm -c 'sh "C:\Users\vagrant\AppData\Local\Temp\moy4ecnq.pis/script20150119-10500-1hab0fh.sh"' ----
STDOUT: 
STDERR: sh: line 1: /opt/chef/bin/chef-client: No such file or directory
An error occurred executing a remote WinRM command.

Shell: powershell
Command: sh "C:\Users\vagrant\AppData\Local\Temp\moy4ecnq.pis/script20150119-10500-1hab0fh.sh"
if ($LASTEXITCODE) { exit $LASTEXITCODE } else { exit 0 }
Message: Command execution failed with an exit code of 127
---- End output of vagrant winrm -c 'sh "C:\Users\vagrant\AppData\Local\Temp\moy4ecnq.pis/script20150119-10500-1hab0fh.sh"' ----
Ran vagrant winrm -c 'sh "C:\Users\vagrant\AppData\Local\Temp\moy4ecnq.pis/script20150119-10500-1hab0fh.sh"' returned 1]
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
``̀`

**Comment by Annih** [comment]
Hi,

In deed the latest test-kitchen version changed some attributes for the chef-zero provisioner.
You should override the following attributes in your kitchen.yml:
```yml
chef_client_path: C:/opscode/chef/bin/chef-client
chef_omnibus_root: C:/opscode/chef/
ruby_bindir: C:/opscode/chef/embedded/bin
```
These values should be the default ones on Windows.

Your .kitchen.yml file should looks similar to:
```yml
---
platforms:
- name: windows
  driver_plugin: vagrant_winrm
  provisioner:
    name: chef_zero
    sudo: false
    root_path: C:/var/chef
    chef_client_path: C:/opscode/chef/bin/chef-client
    chef_omnibus_root: C:/opscode/chef/
    ruby_bindir: C:/opscode/chef/embedded/bin
  driver_config:
    box: windows
```
